#to create any image we need base image
#here we use base image 8.3.0-fpm-alpine
#we write in this form php:8.3.0-fpm-alpine , because php: here vendor name we have to wirte it always firt while using package as base iamge
#here fpm means compatiable with ngix php: means first vendor name here php
FROM php:8.3.0-fpm-alpine as app
# for multi-build we use as app alies so that we can give referrence this to other build



# Useful PHP extension installer image, copy binary into your container
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
# it's a php extanition installer and so this will really help us
# because xdebug is required a lot of other extensions and a lot of other software to be installed 
# in order to install xdebuger but with this php extension installer it can take care of all these staff
# we have to run just a simple command





# # docker-php-ext-install to install php extanition
# RUN docker-php-ext-install pdo pdo_mysql

# so with above php-extension-installer this would be like
RUN set -eux; \
    install-php-extensions pdo pdo_mysql;
# -eux it is a linix command it's means exit on errors exit on any unset variables
# and print every command as it is executed



# for mysqli if you want
# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli



# allow super user - set this if you use Composer as a
# super user at all times like in docker containers
ENV COMPOSER_ALLOW_SUPERUSER=1
# now we want to obtain composer we actually want it insisde our image of 
# our container not inside its own container
# for that we are goining getting a image and copying it into our own
# we can do this like, for this we are going to getting image and copying it our own




# obtain composer using multi-stage build
# https://docs.docker.com/build/building/multi-stage/
COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer
# Copy means copy image
# --from means from here from image compsoer:2.4
# /usr/bin/composer this ithe compser past
# /usr/bin/composer  it our own path




#Here, we are copying only composer.json and composer.lock (instead of copying the entire source)
# right before doing composer install.
# This is enough to take advantage of docker cache and composer install will
# be executed only when composer.json or composer.lock have indeed changed!-
# https://medium.com/@softius/faster-docker-builds-with-composer-install-b4d2b15d0fff

# now to copy my compser.json and my compsoer.lock files
# the reason i am doing this is to take advantage of the docker cache because
# when it see that something has changed it will rebuild the entire image from that step to own words
# so when it see nothing has changed then it will grap path from cache
# so composer install will be executed only if there are cahgen in composer.json and composer.lock

COPY ./app/composer.* ./
# ./app/composer.* this is our own path
# here * in composer.* means composer.lock or composer.json
# ./ this is the path in the container



# install
RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction
# RUN is used to execute any command of teh current image
# is running the composer install command with specific options. Let's break down each option:
# --prefer-dist: Composer will try to install the distribution (i.e., pre-packaged archive) of the package if possible, rather than cloning the source repository.
# --no-dev: Composer will not install packages listed in the require-dev section of the composer.json file. This is useful in production environments where development dependencies are not needed.
# --no-scripts: Composer will not execute scripts defined in the composer.json file. This is often used in production to speed up the installation process and avoid running unnecessary scripts.
# --no-progress: Composer will not show progress bars during the installation process.
# --no-interaction: Composer will not ask for any interactive input and will use default values for any prompts.








# copy application files to the working directory
COPY ./app .

# run composer dump-autoload --optimize
RUN composer dump-autoload --optimize


# multi-stage builds
# it's little bit difficult to understand
# becausely whe we doing here From base image then we add other layers to it
# multi-stage builds
# it's little bit difficult to understand
# becausely whe we doing here From base image then we add other layers to it


# Dev image
# This stage is meant to be target-built into a separate image
# https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage
# https://docs.docker.com/compose/compose-file/#target
FROM app as app_dev
# here we use app_dev as allies we can use any name here
# one resise choseing this allies app_dev we will use it for development purpose
# one reason for multi-stage build is that if we dont want run one 
# build for exemple this part is ony for development not for production 
# because we will install dependencies or extensions which only for development
# simple can not run this build
 

#  Xdebug has different functionalities we can use as profiler, step debugger
#  or we can et it off because it can be quite process heavy and quite instrusive
#  so default we set debug mode off



# Xdebug has different modes / functionalities. We can default to 'off' and set to 'debug'
# when we run docker compose up if we need it
ENV XDEBUG_MODE=off
# here we use env varialbe, there we set default value off,
# as it is env variable so in env we can set it's value whatever we what
# let for enable debuging we can set it's value in evn debug


# php configrations for xdebuger to work
# we have to crate ini file which will have some settings below its the path of that file
# Copy xdebug config file into container
COPY ./php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# there we are doing some special PHP configrations in order to X deuger to work
# here are going to create .ini file which has some settings inside it




# here we install xdebuger
# Install xdebug
RUN set -eux; \
	install-php-extensions xdebug





